# error_codes.py

EMPTY_QUERY = "EMPTY_QUERY"
QUERY_TOO_SHORT = "QUERY_TOO_SHORT"
QUERY_TOO_LONG = "QUERY_TOO_LONG"
INVALID_QUERY = "INVALID_QUERY"

MODEL_NOT_READY = "MODEL_NOT_READY"
VECTOR_INDEX_NOT_READY = "VECTOR_INDEX_NOT_READY"

TRANSLATION_FAILED = "TRANSLATION_FAILED"
NORMALIZATION_FAILED = "NORMALIZATION_FAILED"

INTERNAL_RETRIEVAL_FAILED = "INTERNAL_RETRIEVAL_FAILED"
EXTERNAL_RETRIEVAL_FAILED = "EXTERNAL_RETRIEVAL_FAILED"
NO_RESULTS = "NO_RESULTS"

RERANK_FAILED = "RERANK_FAILED"
SUMMARY_GENERATION_FAILED = "SUMMARY_GENERATION_FAILED"

INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"