# app/core/error_codes.py

EMPTY_QUERY = "EMPTY_QUERY"
QUERY_TOO_SHORT = "QUERY_TOO_SHORT"
QUERY_TOO_LONG = "QUERY_TOO_LONG"
INVALID_QUERY = "INVALID_QUERY"

MODEL_NOT_READY = "MODEL_NOT_READY"
VECTOR_INDEX_NOT_READY = "VECTOR_INDEX_NOT_READY"

TRANSLATION_FAILED = "TRANSLATION_FAILED"
NORMALIZATION_FAILED = "NORMALIZATION_FAILED"

INTERNAL_RETRIEVAL_FAILED = "INTERNAL_RETRIEVAL_FAILED"
EXTERNAL_RETRIEVAL_FAILED = "EXTERNAL_RETRIEVAL_FAILED"
NO_RESULTS = "NO_RESULTS"

RERANK_FAILED = "RERANK_FAILED"
SUMMARY_GENERATION_FAILED = "SUMMARY_GENERATION_FAILED"

AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
AUTH_USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS"
AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
AUTH_USERNAME_ALREADY_EXISTS = "AUTH_USERNAME_ALREADY_EXISTS"
AUTH_ACCOUNT_INACTIVE = "AUTH_ACCOUNT_INACTIVE"
AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED"
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_REFRESH_TOKEN_REVOKED = "AUTH_REFRESH_TOKEN_REVOKED"
AUTH_PASSWORD_MISMATCH = "AUTH_PASSWORD_MISMATCH"
AUTH_PASSWORD_WEAK = "AUTH_PASSWORD_WEAK"
AUTH_INVALID_USERNAME = "AUTH_INVALID_USERNAME"
AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"

ADMIN_POLICY_NOT_FOUND = "ADMIN_POLICY_NOT_FOUND"
ADMIN_INVALID_ROLE = "ADMIN_INVALID_ROLE"
ADMIN_CANNOT_DEMOTE_LAST_SUPERUSER = "ADMIN_CANNOT_DEMOTE_LAST_SUPERUSER"
ADMIN_TARGET_USER_NOT_FOUND = "ADMIN_TARGET_USER_NOT_FOUND"

INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"